# Generated by Django 2.0.6 on 2018-06-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180612_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
